server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  # zipkin/sleuth链路跟踪
  zipkin:
    base-url: http://localhost:9411
zipkin:
  storage:
    type: mysql
  sleuth:
    sampler:
      # 采样值介于0到1之间,1表示全部采集
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"